### ISSUE TITLE
Not working on XCode 6.1.1

### ISSUE THREAD

**Issue by buguibu** [xlc/XLCXcodeAssist#2]
With Xcoe 6.1.1 (6A2008a) i'm not able to raise the popup, installing this with Alcatraz or by cloning&building, almost for protocol methods.

**Comment by xlc** [comment]
It still working for me with Xcode 6.1.1. Can you provide some code that auto suggestion doesn't work?

**Comment by buguibu** [comment]
In any class that must implement a protocol, XCode shows the warning but no "fitx-it" suggestion is shown.

**Comment by xlc** [comment]
Should be fixed.
