### ISSUE TITLE
No Fix-it popup on Xcode 6.4

### ISSUE THREAD

**Issue by Hs-Yeah** [xlc/XLCXcodeAssist#4]
I added Xcode 6.4 DVTPlugInCompatibilityUUID in the Info.plist and built it, but I can't see Fix-it popup on Xcode 6.4.

**Comment by xlc** [comment]
I just tried it and it is working after Xcode prompt me to load unexpected code bundle. 
You can try uninstall the plugin and reinstall it again.
Feel free to reopen this issue if it still not working.
