### ISSUE TITLE
Xcode 8 ?

### ISSUE THREAD

**Issue by Alex293** [xlc/XLCXcodeAssist#8]
Is this repos still maintained and or working with the new Xcode 8 ?

**Comment by xlc** [comment]
Xcode 8 doesn't support plugin anymore. https://github.com/alcatraz/Alcatraz/issues/475
I might port this to Xcode Source Editor Extension, but it won't be anytime soon.

**Comment by Alex293** [comment]
You're right already forgot about that. Too bad I'd loved to try this repo. Can you update issue when you will start your port ?

**Comment by xlc** [comment]
Sure. Will let you know when I start the port.
